apiVersion: apps/v1
kind: Deployment
metadata:
  name: potato-facts
  labels:
    app: potato-facts
spec:
  replicas: 3
  selector:
    matchLabels:
      app: potato-facts
  template:
    metadata:
      labels:
        app: potato-facts
    spec:
      containers:
        - name: potato-facts
          image: index.docker.io/armory/potatofacts:v1
          env:
            - name: APPLICATION_NAME
              value: potatofacts
          ports:
            - name: http
              containerPort: 9001
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 9001
              scheme: HTTP
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 9001
              scheme: HTTP
