apiVersion: v1
kind: Service
metadata:
  name: potato-facts
spec:
  selector:
    app: potato-facts
  ports:
    - protocol: TCP
      port: 9001
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-conf
data:
  nginx.conf: |
    user nginx;
    worker_processes  3;
    error_log  /var/log/nginx/error.log;
    events {
      worker_connections  10240;
    }

    http {
      server {
        listen 9001;
        location / {
          proxy_http_version 1.1;
          proxy_set_header Connection "";
          proxy_pass http://potato-facts:9001;
        }
      }
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: proxy
spec:
  containers:
    - name: proxy
      image: nginx
      ports:
        - containerPort: 8000
      volumeMounts:
        - mountPath: /etc/nginx
          readOnly: true
          name: proxy-conf
        - mountPath: /var/log/nginx
          name: log
  volumes:
    - name: proxy-conf
      configMap:
        name: proxy-conf
        items:
          - key: nginx.conf
            path: nginx.conf
    - name: log
      emptyDir: {}
