version: v1
kind: kubernetes
application: potato-facts
# targets start ----------------------------------------------------------------
targets:
  staging:
    account: kind-matt-cluster-1
    namespace: potato-facts-staging
    strategy: rolling
    constraints:
      beforeDeployment:
        - runWebhook:
            name: Call_TF_Destory_Job
        - pause:
            duration: 10
            unit: seconds        
  prod:
    account: kind-matt-cluster-1
    namespace: potato-facts-prod
    strategy: rolling
    constraints:
      dependsOn: ["staging"]
      beforeDeployment:
        - runWebhook:
            name: Call_TF_Run_Job
        - pause:
            duration: 1
            unit: seconds            
# targets end ----------------------------------------------------------------

manifests:
  # This tutorial uses URLs to ensure a simple first-time deployment experience.
  # You can also use relative file paths to define manifest locations.
  - path: https://raw.githubusercontent.com/armory-io/cdaas-examples/main/hello-armory/manifests/potato-facts-v1.yaml
  - path: https://raw.githubusercontent.com/armory-io/cdaas-examples/main/hello-armory/manifests/potato-facts-service.yaml
  - path: https://raw.githubusercontent.com/armory-io/cdaas-examples/main/hello-armory/manifests/staging-namespace.yaml
    targets: ["staging"]
  - path: https://raw.githubusercontent.com/armory-io/cdaas-examples/main/hello-armory/manifests/prod-namespace.yaml
    targets: ["prod"]


webhooks:
  - name: Call_TF_Run_Job
    method: POST
    uriTemplate: https://app.terraform.io/api/v2/runs
    networkMode: direct
    disableCallback: true
    headers:
      - key: Authorization
        value: Bearer {{secrets.tf_token}}

      - key: Content-Type
        value: application/vnd.api+json
    bodyTemplate:
      inline:  >-
        {
            "data": {
                "attributes": {
                    "auto-apply": true,
                    "is-destroy": false,
                    "refresh": true,
                    "refresh-only": false
                },
                "relationships": {
                    "workspace": {
                        "data": {
                            "type": "workspaces",
                            "id": "ws-zemTyWM6PsWtf39t"
                        }
                    }
                },
                "type": "runs"
            }
        }
    retryCount: 3

  - name: Call_TF_Destory_Job
    method: POST
    uriTemplate: https://app.terraform.io/api/v2/runs
    networkMode: direct
    disableCallback: true
    headers:
      - key: Authorization
        value: Bearer {{secrets.tf_token}}

      - key: Content-Type
        value: application/vnd.api+json
    bodyTemplate:
      inline:  >-
        {
            "data": {
                "attributes": {
                    "auto-apply": true,
                    "is-destroy": true,
                    "refresh": true,
                    "refresh-only": false
                },
                "relationships": {
                    "workspace": {
                        "data": {
                            "type": "workspaces",
                            "id": "ws-zemTyWM6PsWtf39t"
                        }
                    }
                },
                "type": "runs"
            }
        }
    retryCount: 3

strategies:
  rolling:
    canary:
      steps:
        - setWeight:
            weight: 100
